version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: dayly
      timezone: Europe/Amsterdam

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: dayly
      timezone: Europe/Amsterdam