version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/Amsterdam
      

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/Amsterdam