BaseURL = "https://www.goazure.nl/"
# BaseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Go Azure Meetup"
theme = "castanet"
canonifyurls = false
buildFuture = false
buildDrafts = false
dataDir = "data"
archetypedir = "archetypes"
pagination.pagerSize = 9
# googleAnalytics = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[permalinks]
	page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"
	sponsor = "/:filename"
	redirect = "/:filename"

[outputs]
  home = ["HTML", "RSS"]#, "JSON"]
  page = ["HTML", "RSS"]

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
  name = "About"
  identifier = "about"
  url = "/about"
[[Menu.Main]]
  name = "Contact"
  identifier = "contact"
  url = "/contact"
[[Menu.Main]]
  name = "Guests"
  identifier = "guests"
  url = "/guest"
# [[Menu.Main]]
#   name = "Resources"
#   identifier = "resources"
#   url = "#!"
# [[Menu.Main]]
#   name = "Meetups"
#   identifier = "meetups"
#   url = "/meetups"
#   parent = "resources"
# [[Menu.Main]]
#   name = "Sponsor"
#   identifier = "sponsor"
#   url = "/sponsorship"

[params]
# hide = true
mainSections = ["episode"]
site_theme = "blue"
site_layout = "grid"
enable_jumbo = "false"
favicon = "favicon.ico"
copyright_notice = "Copyright 2021 [Go Azure](https://www.goazure.nl)"
# mailchimp_subscribe = ""
youtube_subscribe = "https://www.youtube.com/@goazure?sub_confirmation=1"
# rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "This vibrant community is where Azure enthusiasts of all levels unite to explore the vast universe of Azure and cloud computing. <p>Our mission is to foster a collaborative environment where we can exchange insights, experiences, and the latest trends in Azure. Whether you're intrigued by the intricate dance between VMs, PaaS, Container Solutions, and FaaS, or weighing the merits of Storage Accounts against Azure SQL, this is your go-to hub for all things Azure."
# media_prefix = ""
  [params.feed]
    copyright = "Copyright 2025 Go Azure" #do not use markdown in this field; it is used in the feed

  [params.social]
    github = "https://github.com/GoAzure-meetup"
    # facebook = ""
    # facebook_admin = [""]  # This needs to be a page admin to get domain insights
    # twitter = "arresteddevops"
    # twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    # instagram = ""
    youtube = "@goazure"

  [params.authors]
    [params.authors.Daniel]
      name = "Daniel Paulus"
      Pronouns = "He/Him"
      thumbnail = "img/host/dpaulus.png"
      bio = "Daniel is a serial conference and meetup organiser. He's Head of Azure Solutions at The Factory, a Cloud Native focused consultancy company, and a Microsoft Azure MVP. He helps companies succeed with Cloud Native technologies and DevOps practices. When not working with tech you can find him out in the woods or fishing at a lake."
      [params.authors.Daniel.social]
        github = "PaulusTM"
        linkedin = "danielpaulus"
        homepage  = "https://www.danielpaulus.com"
    [params.authors.Micha]
      name = "Mischa van den Burg"
      Pronouns = "He/Him"
      thumbnail = "img/host/mvdburg.png"
      bio = ""