name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Tag Release
        run: |
          git tag build-${{ github.run_number }}
          git push origin build-${{ github.run_number }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3

      - name: Build
        run: hugo build --buildFuture --logLevel INFO

      - name: Archive Public folder
        uses: actions/upload-artifact@v4
        with: 
          name: site-release
          path: public/**

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: write
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: site-release
          path: public

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "public"
          skip_api_build: true
          skip_app_build: true

  release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      contents: write
    needs: deploy
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: site-release
          path: public
      
      - name: Zip Artifact
        run: zip -r site-release.zip public

      - name: Create Release
        uses: ncipollo/release-action@v1.19.1
        with:
          name: build-${{ github.run_number }}
          commit: main
          tag: build-${{ github.run_number }}
          artifacts: site-release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: legacy
          draft: false
          prerelease: false
